#!/usr/bin/with-contenv sh

if [ -f $TARGET_DIR/cron.conf ]; then
  echo cron.conf found
  cat $TARGET_DIR/cron.conf > /var/spool/cron/crontabs/abc
fi

# run my servers
HOME=/abc s6-setuidgid abc /usr/local/bin/run_servers.py
