#!/usr/bin/with-contenv sh

TARGET_DIR="/data"

if [ -f $TARGET_DIR/cron.conf ]; then
  echo cron.conf found
  cat $TARGET_DIR/cron.conf > /var/spool/cron/crontabs/abc
fi

# run svn server
s6-setuidgid abc /usr/bin/svnserve -d -r $TARGET_DIR/svn

# run transmission serer
s6-setuidgid abc /usr/bin/transmission-daemon -g $TARGET_DIR/torrent

# run my servers
s6-setuidgid abc /usr/local/bin/run_servers.py

